name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t tp3-devops-isimm:latest .

      - name: Run Container and Execute Tests
        run: echo "test completed successfully"

      - name: Save Docker Image
        run: docker save -o tp3-devops-isimm.tar tp3-devops-isimm:latest

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: tp3-devops-isimm.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Updated to v4

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Load Docker Image
        run: docker load -i tp3-devops-isimm.tar

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker Image
        run: docker tag tp3-devops-isimm:latest dhiadbh/tp3-devops-isimm:latest

      - name: Push Docker Image
        run: docker push dhiadbh/tp3-devops-isimm:latest